export { HomePage as Home } from "./Home"
export { LoginPage as Login } from "./Login"
export { SignUpPage as SignUp } from "./SignUp"
export { AdminPage as Admin } from "./Admin"
export { MoviesPage as Movies } from "./Movies"
export { SeriesPage as Series } from "./Series"
export { UsersPage as Users } from "./Users"
export { DetailPage as Detail } from "./Detail"